### ISSUE TITLE
Better and easier usability of the swapping augmentation method

### ISSUE THREAD

**Issue by attilanagy234** [attilanagy234/TreeSwap#53]
The dependency graph model and the API of the subtree swapping should be improved, so doing experiments with the package in a Jupyter notebook is more comfortable.

**Comment by juditacs** [comment]
Dot graphs can be displayed in Jupyter. Adding a `draw_graph` method would help a lot with verifying new ideas.

**Comment by attilanagy234** [comment]
There is one here: https://github.com/attilanagy234/syntax-augmentation-nmt/blob/main/src/hu_nmt/data_augmentator/wrapper/dependency_graph_wrapper.py#L30
but I need to check if it works as expected in a notebook

**Comment by dorinapetra** [comment]
It works in Jupyter too
