### ISSUE TITLE
Please provide preprocessed dataset in your paper

### ISSUE THREAD

**Issue by vhientran** [attilanagy234/TreeSwap#94]
Hi @attilanagy234 

Thank you very much for releasing the source code of your great work!
I am interested in your paper, so I want to reproduce the reported results. Could you please provide me all the preprocessed datasets used in your paper? For example, datasets are introduced in Table 1, including En-De, En-He, En-Vi, En-Hu.
Many thanks for your help!

Best regards,
Tran.

**Comment by attilanagy234** [comment]
Hey @vhientran, I pushed a Google Drive link pointing to the preprocessed datasets for each language pair + the corresponding train/dev/test splits.
